name: release-deploy

on:
  push:
    branches:
    - release

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - name: deploying remote ssh commands using key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/guest/WEB23-HyupUp
          ./depoly.sh
